# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages

r:
  - release
  - devel
  - oldrel

os:
  - linux
  - osx
  
warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

r_github_packages:
  - r-lib/covr
  - r-quantities/errors

script:
  - git clone https://github.com/r-quantities/quantities.git
  - bash quantities/scripts/check_with_quantities.sh

after_success:
  - Rscript -e 'covr::codecov()'