---
title: 'climatrends: Precipitation and temperature indices for climate variability analysis in R'
tags:
- climate data
- climatology
- earth science
- evapotranspiration
- precipitation data
- R
- reproducibility
- weather data
authors:
  - name: Kauê de Sousa
    orcid: 0000-0002-7571-7845
    affiliation: "1, 2"
  - name: Jacob van Etten
    orcid: 0000-0001-7554-2558
    affiliation: 2
  - name: Svein Ø. Solberg
    orcid: 0000-0002-4491-4483
    affiliation: 1
affiliations:
  - name: Department of Agricultural Sciences, Inland Norway University of Applied Sciences, Hamar, Norway
    index: 1
  - name: Bioversity International, Rome, Italy
    index: 2
citation_author: de Sousa et. al.
date: "`r format(Sys.time(), '%d %B %Y')`"
year: 2020
bibliography: paper.bib
#output: pdf_document
output: rticles::joss_article
journal: JOSS
---

# Summary

Understand how climate variability drives ecological processes is a key approach to provide recommendations for climate adaptation and biodiversity conservation. **climatrends** aims to provide the R [@RCoreTeam] toolkit to compute extreme precipitation and temperature indices that serves as input for climate and crop models [@vanEtten2019; @Kehel2016], trends in climate change [@Aguilar2005; @deSousa2018] and applied ecology [@Prentice1992; @YLiu2018].

[...continue...]

# Methods and features

## Implementation

Four main functions are provided, `ETo()`, `GDD()`, `rainfall()` and `temperature()` with methods [@RCoreTeam] for classes 'data.frame', 'matrix' (or array), and 'sf' [@sf]. 

[...continue...]

## Growing degree-days

Growing degree-days (gdd) is an heuristic tool in phenology that measures heat accumulation and is used to predict plant and animal development rates [@Prentice1992]. Growing degree-days are calculated by taking the integral of warmth above a base temperature ($T_{0}$). The function `GDD()` applies by default the following equation.

Equation [1]

$$GDD = \frac{T_{max} + T_{min}}{2} - T_{0}$$

Where $T_{max}$ is the maximum temperature in the given day, $T_{min}$ is the minimum temperature in the given day and $T_{0}$ is the minimum temperature for growth (as per the physiology of the focal organism). 

For cold environments, where $T_{min}$ may be lower than $T_{0}$, there are two variants of the previous equation to adjust either $T_{mean}$ (variant A) or $T_{min}$ (variant B). The variant A changes $T_{mean}$ to $T_{0}$ if $T_{mean} < T_{0}$ and is expressed as follows.

Equation [2]

$$ GDD = max \left(\frac{T_{max} + T_{min}}{2} - T_{0}, \; 0 \right)$$

The variant B, is calculated using Equation 1, but adjusts $T_{min}$ to $T_{0}$ if $T_{min} < T_{o}$, and is adjusted as follows.

Equation [3]

$$ T_{min} < T_{o} \; \rightarrow \; T_{min} = T_{o} $$

In `GDD()` these equations are defined as 'default', 'variant_a' and 'variant_b', respectively, and can be selected using the argument `equation`.

Additionally, the function may return the number of days that a given organism required to reach a certain number of accumulated degree-days or the raw gdd in each observed day. These values are defined by 'ndays' or 'gdd' and can be adjusted using the argument `return.as`. The required accumulated gdd is defined with argument `degree.days`. For example, the Korean pine (*Pinus koraiensis*) requires 105 $^\circ C$ accumulated gdd to onset of photosynthesis [@JWu2013]. In that case, the function will calculate the growing degree-days ($gdd$) and sum up the values until it reaches the defined gdd (105 $^\circ C$) and return the number of days needed in the given season ($GDD_{ndays}$), as follows.

Equation [4]

$$\parallel GDD_{ndays} \parallel \: = \; \sum^{ggd_1}_{gdd_n}$$


## Reference evapotranspiration

The reference evapotranspiration measures the influence of the climate on a given organism (generally a crop species) water needs [@Brouwer1986]. The function `ETo()` applies the Blaney-Criddle method, a general theoretical method used when only air-temperature is available locally. It should be noted that this method is not very accurate and aims to provide the order of magnitude of evapotranspitation. The reference evapotranspiration is calculated using the following equation.

Equation [5]

$$ETo = p \times \left(0.46 \times \frac{T_{max} + T_{min}}{2} + 8 \right) \times K_c$$

Where $p$ is the mean daily percentage of annual daytime hours, $T_{max}$ is the maximum temperature, $T_{min}$ is the minimum temperature, and $K_c$ is the factor for organism water need may change according to the growth stage.

The percentage of daytime hours ($p$) is calculated internally by most methods in `ETo()` (except the array method) using the given latitude (taken from the inputted `object`) and date (taken from the inputted `day.one`). It matches the latitude and date with a table of daylight percentage derived from Brouwer and Heibloem [-@Brouwer1986]. The table can be verified using `climatrends:::daylight`.

# Examples

## Common beans

Replicate part of the analysis in van Etten et al [-@vanEtten2019] with the beans data to show how we can use this package to capture the influence of climate variability on crop performance. The idea is to show the same PlackettLuce Tree.

## Time series 

Pick some random points in Norway (or Scandinavia??) and check how the trends on temperature indices over the last 20 years. 

## Seed germination or some GDD related analysis

Use the data from seed germination or crop growth to compute GDD. How many GDD a seed need to become a seedling?

# Further development

Integration with other datasets as they become available in `R` via API client packages. New indices related to the physiology of crops to be implemented while I work on the rice data.

# Acknowledgements

This work was supported by The Nordic Joint Committee for Agricultural and Food Research (grant num. 202100-2817).

# References